### ISSUE TITLE
Random locking using cart + Sega CD.

### ISSUE THREAD

**Issue by pmasterBR** [ArcadeTV/msu-md-sf2rm#1]
Thank you very much. I wanted to report something about SF remastered, I know it’s still a beta, I don’t know if it’s happening to other people, but I tested it using Cart / CD combo, and it’s with random locking, the game crashes, but the music keeps playing . Again thank you very much for your work.

**Comment by ArcadeTV** [comment]
I will have to setup my MD/CD for testing. I'll continue to work on it but it may take some time.

**Comment by CaveraBR** [comment]
olá desenvolvedor, a mesma coisa aqui, estou rodando no hardware sega-cd e encontro os mesmos problemas que o PmasterBR,  inicio o jogo jogo de 1 a 2 lutas e o jogo trava e a musica continua, acompanharei aqui se tiver correções futuras, parabéns,um belo trabalho

**Comment by ArcadeTV** [comment]
@CaveraBR Ola obrigada! Infelizmente, no momento, há um problema para o qual preciso de ajuda. Espero que continue em breve.

**Comment by ArcadeTV** [comment]
v0.5 is out, took a lot of time but should be better now:
https://github.com/ArcadeTV/msu-md-sf2rm/releases/tag/v0.5#

Please report any issues, thanks!

**Comment by CaveraBR** [comment]
hello developer, congratulations on returning to the game, I'm trying to run the game but this screen appears, both on the console and emulator
![erro do msu](https://user-images.githubusercontent.com/78322208/109571832-05d92a00-7acb-11eb-8193-cb9f63a885b8.png)

**Comment by ArcadeTV** [comment]
please see the section "lockout screen"
http://msu.arcade-tv.de

**Comment by CaveraBR** [comment]
hello developer, sorry for my obvious mistake, I was trying to run the game without the sega cd connected to the megadrive, today I called normally and I come here to tell you that the game is perfect, I played for 2 hours straight and there were no bugs or crashes, it is in perfect conditions of use in the horiginal hardware

**Comment by ArcadeTV** [comment]
Thank you for the feedback. Have a good time!
