### ISSUE TITLE
[MiSTerFPGA] Black screen after Dictator "thank you" splash screen 

### ISSUE THREAD

**Issue by TruREALigion** [ArcadeTV/msu-md-sf2rm#4]
**Patch version**
Are you using the latest patch and soundPack?
Yes
Also tried downloading from:
https://www.youtube.com/watch?v=bRrshI9z5l0&t=138s&ab_channel=CarFlightGamesCFG

**MiSTer FPGA MegaCD core**
Are you playing on an emulator or real hardware?
the latest MiSTerFPGA MegaCD core

**Describe the bug**
Black screen after Dictator "thank you" splash screen.  I can hear the music track during the black screen and then it stops 

**Additional context**
-Followed the **MiSTerFPGA MegaCD core** instructions to rename the **.md rom** into **cart.rom**
-cue and bin (soundpack) is also in the same folder as instructed.  Music track does indeed play after Dictator splash screen.
-Other ArcadeTV MSU-MD patches work fine (ie. Sonic 2, Chiki Chiki Boys, WonderBoy 3) but SF2CE Remastered is the only one I can't get to go

**Comment by ArcadeTV** [comment]
Hmmm... strange.. Let's sort it out!
Have you tried the non-msu remastered rom with the splash screen? Does that also black-out?

If you have a HexEditor handy you can skip Pyron's splash screen and restore the original Capcom entry-point by editing location `0x00000004` from value `$00300000` to `$00008000`.
I haven't had any reports since the last update and I don't have a MiSTer, so I won't be able to test or reproduce the issue.
Do you know if there's an debug output if a game crashes?

**Comment by TruREALigion** [comment]
The regular (GENS/MD core) remastered rom works fine.  Shoutouts to Gabriel Pyron

So I just ran it again and this is what is happening:
1. Pyron splash, plays the **thank you track**
2. press start to proceed
3. SEGA logo, plays another track
4. black screen, plays CAPCOM music track
5. and thats it.

I can try Hex editting the Pyron splash I'm not too technical with the MiSTer so I'll see if there is a way to get some debugging logs.

**Comment by ArcadeTV** [comment]
A wild guess would be that it just plays the tracks from the CD image in their order when the rom crashes and stops when the emulator crashes after that-
I have no option to reproduce it without a MiSTer unfortunately :-/

**Comment by diablonet** [comment]
it runs fine on my mister, I made a video of it: <blockquote class="twitter-tweet"><p lang="und" dir="ltr"> <a href="https://t.co/aIGAJpxPgX">pic.twitter.com/aIGAJpxPgX</a></p>&mdash; Jorge Velazquez (@diablomzt) <a href="https://twitter.com/diablomzt/status/1375446186367275015?ref_src=twsrc%5Etfw">March 26, 2021</a></blockquote>

**Comment by diablonet** [comment]
file names: https://twitter.com/diablomzt/status/1375446287718481921?s=20

**Comment by TruREALigion** [comment]
This folder version works (thank you ArcadeTV):
Street Fighter II' - Remastered Edition (USA) (MSU-MD) [Hack by ArcadeTV v0.5] [Hack by Pyron v1.0] [n]

This version doesn't have the Splash screen.  So the question is:
a. was this caused by the splash screen
b. was it caused by bad rom?  I mean.. it was patched twice technically.  One with Pyron patch, and the next patch ArcadeTV MSU-MD
c. all of the above

**Comment by ArcadeTV** [comment]
I suspect you had a lower version of the rom or a mix of rom.md/cart.rom.
If in doubt I'd suggest getting the latest bps from [github](https://github.com/ArcadeTV/msu-md-sf2rm/releases), the latest soundPack as in the [Readme.md](https://github.com/ArcadeTV/msu-md-sf2rm/blob/master/README.md)

**Comment by diablonet** [comment]
want me to share the crc of every file ?

**Comment by ArcadeTV** [comment]
Thanks for asking, but you don't have to. The CRC of the source rom is given, that should work.
